CREATE TABLE IF NOT EXISTS urls (
    id SERIAL PRIMARY KEY,
    short_key VARCHAR(50) UNIQUE,
    long_url VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
